<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Onesie</name>
   <tag></tag>
   <elementGuidId>e0a3e172-6ebb-4f16-abe9-c24064fcf22b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='item_2_img_link']/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#item_2_img_link > img.inventory_item_img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>09ace594-8c32-4723-aa55-4cd0b4ef305e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Sauce Labs Onesie</value>
      <webElementGuid>15ac8bb4-9b28-40a1-a2bd-1a26c1bf3eec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>inventory_item_img</value>
      <webElementGuid>2e02a2b7-6568-4de3-829d-2fe6bd02e8f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/static/media/red-onesie-1200x1500.1b15e1fa.jpg</value>
      <webElementGuid>9c3fca42-43d3-479e-baa3-b93e5449f533</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;item_2_img_link&quot;)/img[@class=&quot;inventory_item_img&quot;]</value>
      <webElementGuid>daf9af83-6d79-4366-87ef-d83c24ff96da</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='item_2_img_link']/img</value>
      <webElementGuid>7ddc4e32-9045-47ee-82d9-2d4e08efc896</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Sauce Labs Onesie']</value>
      <webElementGuid>3ba7fcd3-7ad0-4745-bb83-8fd7f53f0308</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/a/img</value>
      <webElementGuid>d15fcf0a-cb9e-4809-9c60-d43c0f5e7361</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'Sauce Labs Onesie' and @src = '/static/media/red-onesie-1200x1500.1b15e1fa.jpg']</value>
      <webElementGuid>2842ea20-e4f2-4f44-a927-560f658f589a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
