<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_T-shirt(Red)</name>
   <tag></tag>
   <elementGuidId>b85a03fd-d520-4647-b60c-f291f85ba0cf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='item_3_img_link']/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#item_3_img_link > img.inventory_item_img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>38896e05-52f2-447e-b5d2-779369e48319</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Test.allTheThings() T-Shirt (Red)</value>
      <webElementGuid>f533717d-63b3-4424-b0f9-1424726b5846</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>inventory_item_img</value>
      <webElementGuid>2d95f01f-17f6-461e-8a3a-0a3aed1b3081</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/static/media/red-tatt-1200x1500.e32b4ef9.jpg</value>
      <webElementGuid>af84429a-b463-4b3f-b85c-22f3db1cafd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;item_3_img_link&quot;)/img[@class=&quot;inventory_item_img&quot;]</value>
      <webElementGuid>5dfae333-ef7d-49b5-9fe3-8c15b1e124e8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='item_3_img_link']/img</value>
      <webElementGuid>da4eff56-05f5-4846-a0a7-3b5c199722d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Test.allTheThings() T-Shirt (Red)']</value>
      <webElementGuid>b7b17077-a4b0-4486-ab75-7a98babd9e39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/a/img</value>
      <webElementGuid>063ff8e7-33b1-40b4-a4fc-c60585939822</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'Test.allTheThings() T-Shirt (Red)' and @src = '/static/media/red-tatt-1200x1500.e32b4ef9.jpg']</value>
      <webElementGuid>524b7a3c-c5e7-4b59-883e-cb4ac68846ca</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
